### ISSUE TITLE
Domain check SPF wrong on -all/~all

### ISSUE THREAD

**Issue by rvd0167** [antedebaas/DMARC-Reports#146] opened 2024-08-22 09:28 UTC
The outcome of the domein SFC check does not show the minus (-) or tilde (~)
eg "-all" becomes "all"

Our SPF-record: 
comprax.nl      text = "v=spf1 include:_spf.comprax.nl -all"

Result: 
![image](https://github.com/user-attachments/assets/2b484b31-ed3d-45e9-b994-5552cb417ad9)

**Comment by antedebaas** [comment] 2024-08-22 17:30
cant reproduce:
![image](https://github.com/user-attachments/assets/efd382a6-cb8c-4d0a-bc46-456e503e7bf6)

**Comment by antedebaas** [comment] 2024-08-22 17:38
thank you.

fixed in 1.20.1

**Closed as completed by antedebaas** 2024-08-22 17:38 UTC

**Comment by rvd0167** [comment] 2024-08-22 17:45
1.20.1 no problems.
Thanx
