### ISSUE TITLE
BUG: twice or triple mail retrieval

### ISSUE THREAD

**Issue by bundyland** [antedebaas/DMARC-Reports#59] opened 2024-03-22 12:13 UTC
Hi Ante,

I have noticed that for some time now, the mails have been retrieved three times in a row although according to CRON this should only happen once every hour:

![Screenshot 2024-03-22 130009](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/f3e82729-6151-453d-90f5-fb53baac51a1)

As a result, if a new report is available in the mailbox, it is imported twice or three times. For example today:

![import](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/b14e7719-4ec4-40bd-81c0-5e01bf4f9a0c)

I have checked the mailbox, but this report came in definitely only once and not repeated.

As always, many thanks for your work and support.

**Comment by antedebaas** [comment] 2024-04-02 17:02
i cant reproduce this.
please check if you dont run the command multiple times at once

**Comment by bundyland** [comment] 2024-04-14 12:12
> i cant reproduce this. please check if you dont run the command multiple times at once

Hi Ante,

sorry to re-open this issue, but I still have the same problem even with the latest release.

As I don't run the mail retrieval command manually, it must be some kind of bug with the integrated CRON scheduler.
I have noticed that this doesn't happen immediately after starting the containers, but some times later. Maybe a day or two.

My logs look like this:

![Screenshot 2024-04-14 140330](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/7035c261-ca72-45b6-bdc4-57042c73d4ab)

I have just restarted the containers and the mailcheck happens just once in the moment, but later it will happen twice or even triple for sure. Normally I wouldn't care, but unfortunately the new arrived reports are also imported multiple times. That is the real problem.

Is there a way to completely deactivate the integrated CRON mailcheck? I would rather prefer to carry out the mail query manually to avoid this problem. I have deleted the corresponding line from the docker-compose.yml, but this does not seem to deactivate the mail check.

Thank you.

**Comment by antedebaas** [comment] 2024-04-14 12:54
i dont have any option to disable the cron implemented no.

can you check the contents of /etc/crontabs/root for me?
it should never be called more than once at a time

**Comment by bundyland** [comment] 2024-04-14 13:13
Sure, that looks like this:

![Screenshot 2024-04-14 140330](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/134013618/ff4bfb49-85ad-42b2-b018-461183e954d8)

**Comment by antedebaas** [comment] 2024-04-14 14:02
Hmm looks normal to me. It should check only once per hour.
Which it is not doing. I think your calling the check mail command from somewhere else (docker host?) every 30 mins
It’s definitely being called from somewhere else. The cron only gets executed on the whole hour.

**Comment by bundyland** [comment] 2024-04-14 14:30
I know it sounds strange, but I really don't execute the cron manually. And all other applications that I run in parallel in Docker should not actually have any influence to the Dmarc reader.

Well, I have now changed the cron scheduler to check only once per year and will do the checks manually through a script. If there is really something else who causes the unexpected checks, it should still appear in the logs then. Let's see.

Thanks again for your help.

**Comment by antedebaas** [comment] 2024-04-14 14:38
I remember differently; see #27 :)

**Comment by bundyland** [comment] 2024-04-14 14:41
Yes, but this was before you have created the possibility to change the cron via the docker compose file. Since that I had removed my script because it was useless. :)

**Comment by antedebaas** [comment] 2024-04-14 15:06
ah ok.
and just to check you are not running multiple instances of it? (multiple dmarc-report containers and 1 database for example)

**Comment by antedebaas** [comment] 2024-04-14 15:10
guess what i managed to reproduce locally:
![image](https://github.com/antedebaas/DMARC-SMTPTLS-Reports/assets/5467398/4944d6db-cb5e-4452-b5bd-e5cc53b581d9)
ill be looking into this

**Comment by bundyland** [comment] 2024-04-14 15:13
Hahaha, I thought I'm too stupid. :-)

Thank you!

**Comment by antedebaas** [comment] 2024-04-14 15:33
no the container startup script was at fault.
it would add a new checkmail.sh line to the crontab on each start of the container
fixed in 1.9.4

**Closed as completed by antedebaas** 2024-04-14 15:33 UTC

**Comment by bundyland** [comment] 2024-04-14 16:07
Great job, Ante. Thank you very much!
